### ISSUE TITLE
写了几个java文件还带警告的

### ISSUE THREAD

**Issue by RikaShiro** [tozyx/GenshinPiano#2]
看笑了 你戏是真的多

**Comment by tozyx** [comment]
我不知道你所说的戏指什么，有建议请直接提出；我不是计算机专业的，也不是表演专业的，也没上过过任何编程语言的专业课，正通过抽时间自学解决力所能及的事情。能让你开心，并让我知晓，我挺满意了；毕竟有dalao莅临我的仓库了。
